### ISSUE TITLE
Translate Bot

### ISSUE THREAD

**Issue by Getauscht** [Altir-Team/genai-localization#8]
Hi, I don't know if it's of interest to you but I may be translating your bot's interface into other languages.
Such as:
Portuguese (pt-BR)
Spanish (es-LA)
Chinese (CN) - It's not my specialty, but I know the language a lot!

**Comment by bit0r1n** [comment]
I am always interested in translating bot into foreign languages. For translating just create pull request with all translated files in new localization folder.

**Comment by Getauscht** [comment]
OK! I will soon be creating a pull with the translations! 👍
